### PR TITLE
Fix: UserSecretStorage is missing PDO::ERRMODE_EXCEPTION

### LINKED ISSUE #46: UserSecretStorage is missing PDO::ERRMODE_EXCEPTION
UserSecretStorage is missing the option array(PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION) in https://github.com/Tiqr/tiqr-server-libphp/blob/develop/library/tiqr/Tiqr/UserSecretStorage.php#L77
Because the error handling does expect exceptions from the PDO calls, errors reading or writing the user secret are not detected at this point, leading to errors later in the authentication process.

### PR DESCRIPTION
**Pull request by pmeulen**
Fixes #46

### CODE REVIEW

File: library/tiqr/tests/Tiqr_UserSecretStorage_PdoTest.php [hunk 1]
```diff
@@ -80,6 +80,24 @@ public function test_it_can_store_and_retrieve_an_user_secret()
...
+                'dsn' => $this->dsn,
+                'username' => 'root',
+                'password' => 'secret',
+                'table' => 'tiqrusersecret_xxx'
+            )
+        );
+        $this->expectException(ReadWriteException::class);
+        $store->setSecret('user-id-1', 'my-secret');
+        $this->expectException(ReadWriteException::class);
+        $store->getSecret('user-id-1');
```
Comment (MKodde) [inline library/tiqr/tests/Tiqr_UserSecretStorage_PdoTest.php:98]: I'm currently not set up to to run this test without hassle. I'm curious. Is the ReadWriteException message relevant to just log to the application log?

And I'm usually in the habit to also check if the expected exception message matches the actual message being thrown. That way: 

1. The reader of the test is informed about the error situation we are testing (assuming the exception message is descriptive)
2. The test becomes more specific. In your case the `ReadWriteException` you are catching might have different messages for your two different test scenarios. But this is not verified here.

I'm fine with leaving it like this. But it might be something to consider.

**Review by MKodde — APPROVED** [review]
Lookin' good!

File: library/tiqr/tests/Tiqr_UserSecretStorage_PdoTest.php (hunk 1 above)
Comment (pmeulen) [reply library/tiqr/tests/Tiqr_UserSecretStorage_PdoTest.php:98]: All I want to test here is that an exception is thrown by PDO when the query fails. The ReadWriteException is converted from the PDO exception such that it will contain the same message. The actual message will depend on the PDO driver used and the actual error encountered. So in real scenario's that message should be informative.
